apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-wiki
  template:
    metadata:
      labels:
        app: app-wiki
    spec:
      containers:
      - name: app-wiki
        image: de.icr.io/namespace-sdo/mongodb


